os:
- linux
language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
- python setup.py install
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: danwos
  password:
    secure: a7cnSZiB2/kgMEpOpjjyfjAlHAGUGD4QVn3IuNNbilLocw7ZGtOFgSpZH+PYNvXSFpZRQadUcoBgGEApwwW/f7uc9fUFPaLRwooqlrS+++0JCSFnRZsSVfPNCphHTdqiwqjIDJ9JSYTYcbpNmmhHChE6WSkI9cSed9mAEWWb33j1231+ip3qzQgO7n6qWFg2uL1bukzXc5bn9DpjmmYi+1NaWnXvEhBCP3CeI+N4FLQF8kdixSyDAuT3tNnobY1LsTdwGaY47lSHEvO9CWZKtUr0SN3/QIQ8/MW+k/kVrLd7KkZUnAL1RMhs9XbogvU1CTmncpxq/8X+sdjU9NVvY3KCcWlckwwj3W1p28YVk9TFLPeBNkwVtaMZzWdDRXoIczyN2jJfUs6o9aFytlA9zCQRvP/Sy+O17I+zf7YhWze69U7QI/24lczXh0/WO2h3jwNx/Te7lV/kGgb99P0OulI/hVF8gO1i4/IAyQI8yoTpb5GiFDc1I8qNARDJoq+Iw3cbDyWjD2uRGcwUPR2AyVFa+9ZoEr8dXgaIFNyaPMiSLEPHrIfDi9HBUF/sEQbWPjqOz/gfuXo0WLrD9i4WEt/m/2PvbAaviR5+Wuv8cvVXIj6BIQgPGa2TXDnGHVId5uy6Qva9o4hFIYolXwljv0eKAdhGmVwh7psmhzWM1Hw=
  on:
    tags: true
    branch: master
